name: 'Add Issue/PR to Project'

on:
  issues:
    types:
      - opened
      - transferred
      - labeled

  pull_request:
    types:
      - opened
      - labeled

jobs:
  add:
    uses: DarkArtek/github-scripts/.github/workflows/add-to-project.yml@main
    with:
      labeled: 'renovate'
      label-operator: 'NOT'
    secrets:
      PROJECT_GITHUB_TOKEN: '${{ secrets.PROJECT_GITHUB_TOKEN }}'