name: 'Check'

on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  build:
    if: github.event_name != 'push'
    uses: DarkArtek/github-scripts/.github/workflows/yarn-run.yml@main
    permissions:
      contents: read
    with:
      scipt: 'build'

  lint:
    uses: DarkArtek/github-scripts/.github/workflows/yarn-list.yml@main
    permissions:
      contents: read
      pull-requests: write

  format:
    if: github.event_name == 'push'
    uses: DarkArtek/github-scripts/.github/workflows/yarn-format.yml@main
    permissions:
      contents: write