name: Lint Dockerfile

on:
  push:
    branches:
      - 'main'
    paths:
      - '**/Dockerfile'
      - '**/.Dockerfile'
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '**/Dockerfile'
      - '**/.Dockerfile'
  workflow_dispatch:

jobs:
  lint:
    uses: DarkArtek/github-scripts/.github/workflows/hadolint.yml@main
    permissions:
      contents: read
      pull-requests: write