name: Check Renovate
on:
  push:
    branches:
      - 'main'
    paths:
      - 'renovate.json'
      - 'renovate-config.json'
      - 'env/renovate/**'
      - '.github/workflows/_check-renovate.yml'
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:


jobs:

  test:
    if: github.event_name != 'schedule'
    uses: ./.github/workflows/yarn-run.yml
    with:
      working-directory: '/env/renovate'
      script: 'test'

  build:
    if: github.event_name != 'schedule'
    uses: ./.github/workflows/yarn-run.yml
    with:
      working-directory: 'env/renovate'
      script: 'build'
    permissions:
      contents: read

  lint:
    if: github.event_name != 'schedule'
    uses: ./.github/workflows/yarn-lint.yml
    with:
      working-directory: 'env/renovate'
    permissions:
      contents: read
      pull-requests: write

  format:
    if: github.event_name != 'pull_request' && github.event_name != 'schedule'
    uses: ./.github/workflows/yarn-format.yml
    with:
      working-directory: 'env/renovate'
    permissions:
      contents: write

