name: Check Prettier

on:
  push:
    branches:
      - main
    paths:
      - 'env/prettier/**'
      - '.github/workflows/_check-prettier.yml'
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/yarn-lint.yml
    with:
      working-directory: 'env/prettier'
      pre-script: 'build'
    permissions:
      contents: read
      pull-requests: write
  format:
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/yarn-format.yml
    with:
      working-directory: 'env/prettier'
      pre-scrip: 'build'
    permissions:
      contents: write