name: Check GitHub

on:
  push:
    branches:
      - 'main'
    paths:
      - 'env/github/**'
      - '.github/workflows/_check-github.yml'

  pull_request:
    types:
      - opened
      - synchronize

  workflow_dispatch:

jobs:
  build:
    if: github.event_name != 'schedule'
    uses: ./.github/workflows/yarn-run.yml
    with:
      working-directory: 'env/github'
      script: 'build'
    permissions:
      contents: 'read'

  lint:
    if: github.event_name != 'schedule'
    uses: ./.github/workflows/yarn-lint.yml
    with:
      working-directory: 'env/github'
    permissions:
      contents: 'read'
      pull-requests: 'write'

  format:
    if: github.event_name != 'pull_request' && github.event_name != 'schedule'
    uses: ./.github/workflows/yarn-format.yml
    with:
      working-directory: 'env/github'
    permissions:
      contents: 'write'