name: HadoLint

on:
  workflow_call:
    inputs:
      reporter:
        required: false
        type: string
        default: 'github-pr-review'

permissions:
  contents: read
  pull-requests: write


jobs:
  lint-on-pull-request:
    if: github.event_name == 'pull_request' && !contains(github.ref, 'renovate')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: HadoLint
        uses: reviewdog/action-hadolint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: ${{ inputs.reporter }}

  lint-on-push:
    if: github.event_name != 'pull_request' && !contains(github.ref, 'renovate')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: HadoLint
        uses: reviewdog/action-hadolint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-check'
